# Generated by Django 5.1 on 2024-09-02 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Description', models.TextField(null=True)),
                ('Details', models.TextField(null=True)),
                ('Rarity', models.PositiveSmallIntegerField(choices=[(0, 'Common'), (1, 'Uncommon'), (2, 'Rare'), (3, 'Epic'), (4, 'Legendary')])),
                ('Type', models.PositiveSmallIntegerField(choices=[(0, 'Helmet'), (1, 'Chestplate'), (2, 'Leggings'), (3, 'Boots'), (4, 'Sword'), (5, 'Staff'), (6, 'Bow')])),
                ('Image', models.ImageField(upload_to='images/items')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.PositiveSmallIntegerField(choices=[(0, 'Store'), (1, 'Auction'), (2, 'BIN')])),
                ('Status', models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'Expired'), (2, 'Purchased')])),
                ('Price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('Stock', models.PositiveIntegerField()),
                ('Listing', models.DateTimeField()),
                ('Expiration', models.TimeField()),
                ('Buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Purchases', to=settings.AUTH_USER_MODEL)),
                ('Seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to=settings.AUTH_USER_MODEL)),
                ('Listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to='store.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('Time', models.DateTimeField()),
                ('Bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bids', to=settings.AUTH_USER_MODEL)),
                ('Listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bids', to='store.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='store.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
